---
starbound_directory: "/home/ubuntu/Starbound"
backup_directory: "/home/ubuntu/Starbound/sbcp/backups"
backup_schedule: hourly
backup_history: 90
log_directory: "/home/ubuntu/Starbound/sbcp/logs"
log_history: 90
log_style: daily
logs_directory: "/home/ubuntu/Starbound/sbcp/logs"
