---
starbound_directory: ~
backup_directory: ~
backup_history: 90
backup_schedule: hourly
log_directory: ~
log_history: 90
log_style: daily
duplicate_names: false
duplicate_kick_msg: "Another player is currently online with your character's name."
restart_schedule: 4
