---
starbound_directory: "/home/ubuntu/Starbound"
backup_directory: "/home/ubuntu/Starbound/sbcp/backups"
backup_history: none
backup_schedule: hourly
log_directory: "/home/ubuntu/Starbound/sbcp/logs"
log_history: 90
log_style: daily
restart_schedule: 4
